global:
  max_parallel: 4

repos:
  - name: HolistiQ
    path: "C:\\Projects\\Personal\\HolistiQ"
    branch: master
    backup_branch_prefix: backup

    

  # - name: repo2
  #   path: D:/git/repo2
  #   branch: develop
  #   backup_branch_prefix: backup